source 'https://rubygems.org'

gem 'activesupport', '7.0.4'
gem 'elasticsearch-xpack', '7.17.1'
gem 'fluentd', '1.15.2'
gem 'fluent-plugin-concat', '2.5.0'
gem 'fluent-plugin-detect-exceptions', '0.0.14'
gem 'fluent-plugin-elasticsearch', '5.2.4'
gem 'fluent-plugin-kubernetes_metadata_filter', '3.1.2'
gem 'fluent-plugin-multi-format-parser', '1.0.0'
gem 'fluent-plugin-opensearch', '1.0.8'
gem 'fluent-plugin-prometheus', '2.0.3'
gem 'fluent-plugin-systemd', '1.0.5'
gem 'oj', '3.13.21'
