source 'https://rubygems.org'

gem 'activesupport', '7.2.1'
gem 'elasticsearch-xpack', '7.17.11'
gem 'fluentd', '1.17.1'
gem 'fluent-plugin-concat', '2.5.0'
gem 'fluent-plugin-detect-exceptions', '0.0.15'
gem 'fluent-plugin-elasticsearch', '5.2.5'
gem 'fluent-plugin-kubernetes_metadata_filter', '3.5.0'
gem 'fluent-plugin-multi-format-parser', '1.1.0'
gem 'fluent-plugin-opensearch', '1.0.10'
gem 'fluent-plugin-prometheus', '2.2.0'
gem 'fluent-plugin-systemd', '1.0.5'
gem 'oj', '3.16.5'
